apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-redis
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: {{ .Values.service.redis.type }}
  ports:
  - port: {{ .Values.service.redis.port }}
    targetPort: 6379
    protocol: TCP
    name: redis
  selector:
    {{- include "voting-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis
