apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-result
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: result
spec:
  type: {{ .Values.service.result.type }}
  ports:
  - port: {{ .Values.service.result.port }}
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    {{- include "voting-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: result
