apiVersion: v1
kind: Service
metadata:
  name: {{ include "voting-app.fullname" . }}-vote
  labels:
    {{- include "voting-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: vote
spec:
  type: {{ .Values.service.vote.type }}
  ports:
  - port: {{ .Values.service.vote.port }}
    targetPort: {{ .Values.service.vote.targetPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "voting-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: vote
